# Site settings
# Enter your own credentials here
title: "Geet's Blog"
email: glahoti6@gatech.edu
description: >
  Tell us about your site
baseurl: "/research-pages" # replace ``/research-pages`` with the name of the parents repository
url: "glahoti6.github.io" # replate ``Materials-Informatics-Lab`` with your Github username
# twitter_username: twitterhandle
github_username:  glahoti6
disqus: glahoti6

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5
